packages:
  - packages/sdk
  - packages/cli
  - packages/infra
  - packages/api-server
  - packages/install-aws
  - packages/appliance.sh

onlyBuiltDependencies:
  - '@pulumi/aws-native'
  - '@pulumi/docker'
  - '@pulumi/docker-build'
  - '@swc/core'
  - esbuild
  - nx
  - protobufjs
